### ISSUE TITLE
Support alt geoms in SQLite databases

### ISSUE THREAD

**Issue by missinglink** [pelias/wof#7]
As per https://github.com/whosonfirst-data/whosonfirst-data/issues/1793#issuecomment-587923979

**Comment by thisisaaronland** [comment]
Passing this along FYI as a reference implementation: 

https://github.com/whosonfirst/go-whosonfirst-browser-sqlite/blob/master/cmd/whosonfirst-browser/main.go#L27-L48

**Comment by missinglink** [comment]
resolved in https://github.com/pelias/wof/commit/aa6f11b5f0eec83e7e933c57f7b9e0a6d471954a
available in `@whosonfirst/wof@0.14.0`
